services:
  redis1:
    container_name: redis1
    image: redis
    command: redis-server --port 6379 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000
    networks:
      - lan_services
  redis2:
    container_name: redis2
    image: redis
    command: redis-server --port 6379 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000
    networks:
      - lan_services
  redis3:
    container_name: redis3
    image: redis
    command: redis-server --port 6379 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000
    networks:
      - lan_services
networks:
  lan_services:
    driver: bridge
